name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Run tests
      run: yarn test --coverage --ci --watchAll=false --passWithNoTests
      env:
        CI: true
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/lcov.info
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  build:
    runs-on: ubuntu-latest
    needs: test
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Build project
      run: yarn build
      env:
        REACT_APP_API_HOST: ${{ vars.REACT_APP_API_HOST }}
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        retention-days: 1
        name: build-files
        path: build
  upload-to-s3:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: ./build
    
    - name: Prepare build files for upload
      run: |
        ls -la ./build
    - name: Deploy to Yandex Cloud Object Storage
      uses: paulvstrashnov/yandex-s3-upload-action@main
      with:
        accessKeyId: ${{ secrets.YC_ACCESS_KEY_ID }}
        secretAccessKey: ${{ secrets.YC_SECRET_ACCESS_KEY }}
        bucket: ${{ secrets.BUCKET }}
        localPath: "./build"
        remotePath: "/"
        clearBucket: false